services:
    app:
        environment:
            FLASK_ENV: development
            VIRTUAL_HOST: localhost
    nginx:
        volumes:
            - ./ssl/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
            - ./ssl/main.crt+chain.pem:/etc/nginx/certs/localhost.crt:ro
            - ./ssl/main.key.pem:/etc/nginx/certs/localhost.key:ro
        ports:
            - "443:443"