version: ‘3’

x-my_flask_webpage: &my_flask_webpage
    image: my_flask_webpage:latest
    tmpfs:
        - /tmp
    #links:
     #   - mail
     #   - redis
     #   - postgres
    networks:
        - back
    read_only: true

services:
  app:
    <<: *my_flask_webpage
    command: uwsgi --ini uwsgi.ini
    #--workers 8 --threads 4
    environment:
      VIRTUAL_PROTO: uwsgi
      VIRTUAL_PORT: 3031
      # Why is needed cfg-File?
    #    SPZ_CFG_FILE: production.cfg
    #volumes:
    # at the moment irrelevent
    networks:
      - front
      - back
  nginx:
    image: jwilder/nginx-proxy:0.9
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - data_static:/static:ro
      - cache_nginx:/var/cache/nginx
      - state_nginx:/etc/nginx
    tmpfs:
      - /run
      - /tmp
    networks:
      - front
    links:
      - app
    read_only: true
    depends_on:
      - app
    ports:
      - "443:443"

volumes:
    cache_nginx: {}
    data_static: {}
    state_nginx: {}


networks:
    front: {}
    back: {}